global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aida-edge'
    static_configs:
      - targets: ['aida-edge:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'aida-core'
    static_configs:
      - targets: ['aida-core:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/varz'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['supabase-db:5432']
    scrape_interval: 60s

  - job_name: 'chroma'
    static_configs:
      - targets: ['chroma:8000']
    metrics_path: '/api/v1/heartbeat'
    scrape_interval: 60s